include $(GNUSTEP_MAKEFILES)/common.make

APP_NAME = Controller
Controller_HEADERS = Controller.h Window.m
Controller_OBJC_FILES = main.m Controller.m Window.m
Controller_RESOURCE_FILES = ControllerInfo.plist

include $(GNUSTEP_MAKEFILES)/application.make